#!/bin/sh
# Copyright (c) 2026 mumuxiao722
# SPDX-License-Identifier: GPL-2.0-only
set -e

udevadm control --reload-rules 2>/dev/null || true
systemctl daemon-reload 2>/dev/null || true
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    systemctl stop sheng-fake-tablet-mode.service sheng-power-key-toggle.service >/dev/null 2>&1 || true
fi

exit 0