#!/bin/sh
# Copyright (c) 2026 mumuxiao722
# SPDX-License-Identifier: GPL-2.0-only
set -e

if [ "$1" = "remove" ] || [ "$1" = "upgrade" ]; then
    systemctl disable sheng-fake-tablet-mode.service sheng-power-key-toggle.service >/dev/null 2>&1 || true
fi

exit 0